# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='\u5546\u4e1a\u4f19\u4f34')),
                ('des', models.CharField(max_length=20, verbose_name='\u63cf\u8ff0')),
                ('shorter_des', models.CharField(max_length=15, verbose_name='\u7b80\u79f0')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u7a0e\u7387')),
                ('supplierflag', models.BooleanField(verbose_name='\u4f9b\u5e94\u5546')),
                ('customerflag', models.BooleanField(verbose_name='\u5ba2\u6237')),
                ('staffflag', models.BooleanField(verbose_name='\u804c\u5458')),
                ('otherflag', models.BooleanField(verbose_name='\u5176\u4ed6')),
                ('cruser', models.CharField(max_length=20, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('crdate', models.DateField(verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('moduser', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4fee\u6539\u7528\u6237')),
                ('moddate', models.DateField(blank=True, null=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u5546\u4e1a\u4f19\u4f34',
            },
        ),
        migrations.CreateModel(
            name='Bptype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='\u7f16\u7801')),
                ('des', models.CharField(max_length=20, verbose_name='\u63cf\u8ff0')),
                ('cruser', models.CharField(max_length=20, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('crdate', models.DateField(verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('moduser', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4fee\u6539\u7528\u6237')),
                ('moddate', models.DateField(blank=True, null=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u63cf\u8ff0')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='\u5730\u5740')),
                ('cruser', models.CharField(max_length=20, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('crdate', models.DateField(verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('moduser', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4fee\u6539\u7528\u6237')),
                ('moddate', models.DateField(blank=True, null=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('upcompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='\u4e0a\u7ea7\u516c\u53f8')),
            ],
        ),
        migrations.CreateModel(
            name='Depts',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='\u90e8\u95e8\u7f16\u7801')),
                ('name', models.CharField(max_length=30, verbose_name='\u90e8\u95e8\u540d\u79f0')),
                ('type', models.IntegerField(choices=[(1, '\u884c\u653f\u90e8\u95e8'), (2, '\u9500\u552e\u90e8\u95e8'), (3, '\u751f\u4ea7\u90e8\u95e8'), (4, '\u751f\u4ea7\u8f85\u52a9\u90e8\u95e8')], default=1, verbose_name='\u90e8\u95e8\u7c7b\u578b')),
                ('cruser', models.CharField(max_length=20, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('crdate', models.DateField(verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('moduser', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4fee\u6539\u7528\u6237')),
                ('moddate', models.DateField(blank=True, null=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u90e8\u95e8\u8d1f\u503a\u4eba')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='\u6240\u5c5e\u516c\u53f8')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Depts', verbose_name='\u4e0a\u7ea7\u90e8\u95e8')),
            ],
        ),
        migrations.CreateModel(
            name='Fcy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=100, verbose_name='\u5730\u70b9')),
                ('des', models.CharField(max_length=100, verbose_name='\u63cf\u8ff0')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='\u5730\u5740')),
                ('cruser', models.CharField(max_length=20, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('crdate', models.DateField(verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('moduser', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4fee\u6539\u7528\u6237')),
                ('moddate', models.DateField(blank=True, null=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='\u6240\u5c5e\u516c\u53f8')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='\u671f\u95f4')),
                ('datedeb', models.DateField(verbose_name='\u5f00\u59cb\u65e5\u671f')),
                ('datefin', models.DateField(verbose_name='\u7ed3\u675f\u65e5\u671f')),
                ('cruser', models.CharField(max_length=20, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('crdate', models.DateField(verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('moduser', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4fee\u6539\u7528\u6237')),
                ('moddate', models.DateField(blank=True, null=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='\u6240\u5c5e\u516c\u53f8')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='\u79d1\u76ee')),
                ('des', models.CharField(max_length=20, verbose_name='\u63cf\u8ff0')),
                ('type', models.IntegerField(choices=[(1, '\u8d44\u4ea7\u7c7b'), (2, '\u8d1f\u503a\u7c7b'), (3, '\u6240\u6709\u8005\u6743\u76ca\u7c7b'), (4, '\u6210\u672c\u7c7b'), (5, '\u635f\u76ca\u7c7b'), (6, '\u5176\u4ed6\u7c7b')], default=1, verbose_name='\u79d1\u76ee\u7c7b\u578b')),
                ('bpsflag', models.BooleanField(verbose_name='\u5546\u4e1a\u4f19\u4f34\u5fc5\u586b')),
                ('Progressflag', models.BooleanField(verbose_name='\u5728\u5efa\u5de5\u7a0b\u5fc5\u586b')),
                ('deptflag', models.BooleanField(verbose_name='\u90e8\u95e8\u5fc5\u586b')),
                ('itmflag', models.BooleanField(verbose_name='\u4ea7\u54c1\u5fc5\u586b')),
                ('crdate', models.DateField(verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('moduser', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4fee\u6539\u7528\u6237')),
                ('moddate', models.DateField(blank=True, null=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='\u6240\u5c5e\u516c\u53f8')),
                ('cruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('upnum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Subject', verbose_name='\u4e0a\u7ea7\u79d1\u76ee')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='\u4f1a\u8ba1\u5e74\u5ea6')),
                ('des', models.CharField(max_length=20, verbose_name='\u63cf\u8ff0')),
                ('cruser', models.CharField(max_length=20, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('crdate', models.DateField(verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('moduser', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4fee\u6539\u7528\u6237')),
                ('moddate', models.DateField(blank=True, null=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='\u6240\u5c5e\u516c\u53f8')),
            ],
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Year', verbose_name='\u4f1a\u8ba1\u5e74\u5ea6'),
        ),
        migrations.AddField(
            model_name='bptype',
            name='acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Subject', verbose_name='\u5f80\u6765\u79d1\u76ee'),
        ),
        migrations.AddField(
            model_name='bptype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='\u6240\u5c5e\u516c\u53f8'),
        ),
        migrations.AddField(
            model_name='bps',
            name='acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Subject', verbose_name='\u5f80\u6765\u79d1\u76ee'),
        ),
        migrations.AddField(
            model_name='bps',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='\u6240\u5c5e\u516c\u53f8'),
        ),
        migrations.AddField(
            model_name='bps',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Bptype', verbose_name='\u7c7b\u522b'),
        ),
    ]
