# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'verbose_name': '\u671f\u95f4'},
        ),
        migrations.RemoveField(
            model_name='month',
            name='year',
        ),
    ]
