# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20160629_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(default=2016, on_delete=django.db.models.deletion.CASCADE, to='general.Year', verbose_name='\u4f1a\u8ba1\u5e74\u5ea6'),
            preserve_default=False,
        ),
    ]
