# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_month_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bptype',
            options={'verbose_name': '\u5546\u4e1a\u4f19\u4f34\u7c7b\u522b'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '\u516c\u53f8'},
        ),
        migrations.AlterModelOptions(
            name='depts',
            options={'verbose_name': '\u90e8\u95e8'},
        ),
        migrations.AlterModelOptions(
            name='fcy',
            options={'verbose_name': '\u5730\u70b9'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': '\u79d1\u76ee'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name': '\u5e74\u5ea6'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='num',
            field=models.CharField(max_length=20, verbose_name='\u79d1\u76ee'),
        ),
    ]
