# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20160629_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bps',
            name='customerflag',
        ),
        migrations.RemoveField(
            model_name='bps',
            name='otherflag',
        ),
        migrations.RemoveField(
            model_name='bps',
            name='staffflag',
        ),
        migrations.RemoveField(
            model_name='bps',
            name='supplierflag',
        ),
    ]
