# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20160629_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='des',
            field=models.CharField(default=1, max_length=20, verbose_name='\u63cf\u8ff0'),
            preserve_default=False,
        ),
    ]
