# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20160704_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='company',
        ),
    ]
