# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_remove_year_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.AlterField(
            model_name='subject',
            name='num',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u79d1\u76ee'),
        ),
    ]
