# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0005_auto_20160629_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name=u'Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=u'ID')),
                ('cruser', models.CharField(max_length=20, verbose_name=u'\u521b\u5efa\u7528\u6237')),
                ('crdate', models.DateField(verbose_name=u'\u521b\u5efa\u65e5\u671f')),
                ('moduser', models.CharField(blank=True, max_length=20, null=True, verbose_name=u'\u4fee\u6539\u7528\u6237')),
                ('moddate', models.DateField(blank=True, null=True, verbose_name=u'\u4fee\u6539\u65e5\u671f')),
                ('type', models.IntegerField(choices=[(1, '\u9884\u7b97\u5bfc\u5165'), (2, '\u9884\u7b97\u5f55\u5165'), (3, '\u9884\u7b97\u8ffd\u52a0'), (4, '\u9884\u7b97\u8c03\u6574')], default=1, verbose_name=u'\u79d1\u76ee\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u9884\u7b97\u5934',
            },
        ),
        migrations.CreateModel(
            name=u'Budgetd',
            fields=[
                ('budget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=u'crm.Budget')),
                ('amt', models.DecimalField(decimal_places=2, max_digits=125)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=u'general.Depts', verbose_name=u'\u9884\u7b97\u90e8\u95e8')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=u'general.Subject', verbose_name=u'\u9884\u7b97\u79d1\u76ee')),
            ],
            options={
                'verbose_name': '\u9884\u7b97\u660e\u7ec6',
            },
            bases=('crm.budget',),
        ),
        migrations.AddField(
            model_name=u'budget',
            name=u'company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=u'general.Company', verbose_name=u'\u6240\u5c5e\u516c\u53f8'),
        ),
        migrations.AddField(
            model_name=u'budget',
            name=u'month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=u'general.Month', verbose_name=u'\u9884\u7b97\u671f\u95f4'),
        ),
        migrations.AddField(
            model_name=u'budget',
            name=u'year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=u'general.Year', verbose_name=u'\u9884\u7b97\u5e74\u5ea6'),
        ),
    ]
