# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name=u'budgetd',
            name=u'amt',
            field=models.DecimalField(decimal_places=2, max_digits=125, verbose_name=u'\u91d1\u989d'),
        ),
    ]
