# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_budget_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name=u'budget',
            name=u'type',
            field=models.IntegerField(choices=[(1, '\u9884\u7b97\u5bfc\u5165'), (2, '\u9884\u7b97\u5f55\u5165'), (3, '\u9884\u7b97\u8ffd\u52a0'), (4, '\u9884\u7b97\u8c03\u6574')], default=1, verbose_name=u'\u9884\u7b97\u7c7b\u578b'),
        ),
    ]
