# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20160704_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetmx',
            name='num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Budget', verbose_name='\u5355\u636e\u53f7'),
        ),
    ]
