# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20160704_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='cruser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u7528\u6237'),
        ),
    ]
