# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_month_des'),
        ('crm', '0007_auto_20160704_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budgetd',
            fields=[
                ('budget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.Budget')),
                ('line', models.IntegerField(verbose_name='\u884c\u53f7')),
                ('amt', models.DecimalField(decimal_places=2, max_digits=125, verbose_name='\u91d1\u989d')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Depts', verbose_name='\u9884\u7b97\u90e8\u95e8')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Subject', verbose_name='\u9884\u7b97\u79d1\u76ee')),
            ],
            options={
                'verbose_name': '\u9884\u7b97\u660e\u7ec6',
            },
            bases=('crm.budget',),
        ),
        migrations.RemoveField(
            model_name='budgetmx',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='budgetmx',
            name='num',
        ),
        migrations.RemoveField(
            model_name='budgetmx',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Budgetmx',
        ),
    ]
