# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20160704_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u5206\u7c7b\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u5206\u7c7b',
                'verbose_name_plural': '\u4ea7\u54c1\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u5173\u952e\u8bcd')),
            ],
            options={
                'verbose_name': '\u5173\u952e\u8bcd',
                'verbose_name_plural': '\u5173\u952e\u8bcd',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u4ea7\u54c1\u540d\u79f0')),
                ('spec', models.CharField(choices=[('1', '\u5927\u53f7'), ('2', '\u4e2d\u53f7'), ('3', '\u5c0f\u53f7')], max_length=1, verbose_name='\u4ea7\u54c1\u578b\u53f7')),
                ('stock', models.IntegerField(default=100, verbose_name='\u5e93\u5b58\u6570\u91cf')),
                ('price', models.DecimalField(decimal_places=2, default=10.0, max_digits=8, verbose_name='\u4ea7\u54c1\u4ef7\u683c')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u4ea7\u54c1\u63cf\u8ff0')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Category', verbose_name='\u4ea7\u54c1\u7c7b\u522b')),
                ('key', models.ManyToManyField(to='crm.Keyword', verbose_name='\u5173\u952e\u8bcd')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1',
                'verbose_name_plural': '\u4ea7\u54c1',
            },
        ),
        migrations.AlterField(
            model_name='budget',
            name='moddate',
            field=models.DateField(blank=True, null=True, verbose_name='u\u4fee\u6539\u65e5\u671f'),
        ),
    ]
