# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20160708_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='key',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
