# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-14 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20160713_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='id',
        ),
        migrations.AlterField(
            model_name='budget',
            name='num',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u5355\u636e\u53f7'),
        ),
    ]
